TodoList/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls", namespace="todo")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/urls.py
from django.urls import path

from todo.views import (
    TagListView,
    TaskListView,
    TagUpdateView,
    TagDeleteView,
    TagCreateView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    task_mark,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("create/", TaskCreateView.as_view(), name="task-create"),
    path("<int:pk>/mark/", task_mark, name="task-mark"),
    path("update/<int:pk>/", TaskUpdateView.as_view(), name="task-update"),
    path("delete/<int:pk>/", TaskDeleteView.as_view(), name="task-delete"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
]

app_name = "todo"

todo/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.name


class Task(models.Model):
    content = models.TextField()
    datetime = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, blank=True, related_name="tasks")

    class Meta:
        ordering = ["is_done", "-datetime"]

    def __str__(self) -> str:
        return self.content

todo/forms.py
from django import forms

from todo.models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ("content", "deadline", "tags")

        widgets = {
            "deadline": forms.DateTimeInput(attrs={"type": "datetime-local"}),
            "tags": forms.CheckboxSelectMultiple(),
        }

todo/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic

from todo.forms import TaskForm
from todo.models import Tag, Task


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    success_url = reverse_lazy("todo:tag-list")
    fields = "__all__"


class TagUpdateView(generic.UpdateView):
    model = Tag
    success_url = reverse_lazy("todo:tag-list")
    fields = "__all__"


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo:tag-list")


class TaskListView(generic.ListView):
    model = Task
    queryset = Task.objects.prefetch_related("tags")


class TaskCreateView(generic.CreateView):
    model = Task
    success_url = reverse_lazy("todo:task-list")
    form_class = TaskForm


class TaskUpdateView(generic.UpdateView):
    model = Task
    success_url = reverse_lazy("todo:task-list")
    form_class = TaskForm


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo:task-list")


def task_mark(request, pk) -> HttpResponseRedirect:
    task = Task.objects.get(pk=pk)
    task.is_done = not task.is_done
    task.save()
    return HttpResponseRedirect(reverse_lazy("todo:task-list"))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <title>Todo List</title>
</head>

<body>
  <div class="container">
    <div class="row">
      <div class="col-sm-2">
        {% block sidebar %}
          {% include "includes/sidebar.html" %}
        {% endblock %}
      </div>

      <div class="col-sm-10">
        {% block content %}
        {% endblock %}
      </div>
    </div>
  </div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todo:task-list' %}" class="link-without-underscore">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo:tag-list' %}" class="link-without-underscore">Tags</a></li>
</ul>

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Are you sure that you want to delete <strong>{{ tag }}</strong></h1>

  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'todo:tag-list' %}" class="btn btn-secondary">No</a>
  </form>
{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    <strong>Tags</strong>
    <div class="right-button">
      <a href="{% url 'todo:tag-create' %}" class="btn btn-primary">Add</a>
    </div>
  </h1>

  <hr>

  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
      {% for tag in tag_list %}
        <tr>
          <td>{{ tag }}</td>
          <td><a href="{% url 'todo:tag-update' pk=tag.pk %}" class="btn btn-secondary">Update</a></td>
          <td><a href="{% url 'todo:tag-delete' pk=tag.pk %}" class="btn btn-secondary">Delete</a></td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There is no tags yet!</p>
  {% endif %}

{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Are you sure that you want to delete <strong>{{ task }}</strong></h1>

  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'todo:task-list' %}" class="btn btn-secondary">No</a>
  </form>
{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/todo/task_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    <strong>TODO list</strong>
    <div class="right-button">
      <a href="{% url 'todo:task-create' %}" class="btn btn-primary">Add task</a>
    </div>
  </h1>
  <br>

  {% if task_list %}
    {% for task in task_list %}
      <div>
        <p><strong>{{ task.content }}</strong>
          {% if task.is_done %}
            <span style="color: green; font-weight: bold">Done</span>
            <span class="right-button">
              <a href="{% url 'todo:task-mark' pk=task.pk %}" class="btn btn-secondary">Undo</a>
            </span>
          {% else %}
            <span style="color: red; font-weight: bold">Not done</span>
            <span class="right-button">
              <a href="{% url 'todo:task-mark' pk=task.pk %}" class="btn btn-success">Complete</a>
            </span>
          {% endif %}
        </p>
        <p>Created: {{ task.datetime }}
          {% if task.deadline %}
            <span style="color: firebrick">Deadline: {{ task.deadline }}</span>
          {% endif %}
        </p>
        <p style="color: darkgray">Tags:
          {% if task.tags.all %}
            {% for tag in task.tags.all %}
              {{ tag }}
            {% endfor %}
          {% else %}
            No tags
          {% endif %}
          <a href="{% url 'todo:task-update' pk=task.pk %}" class="link-without-underscore">Update</a>
          <a href="{% url 'todo:task-delete' pk=task.pk %}" class="link-without-underscore">Delete</a>
        </p>
      </div>
      <hr>
    {% endfor %}
  {% else %}
    <p>There is no tasks yet!</p>
  {% endif %}
{% endblock %}